<?php

namespace AppBundle\Repository;

/**
 * ShoesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoesRepository extends \Doctrine\ORM\EntityRepository
{
}
